### ISSUE TITLE
USER STORY : Select my country from the drop-down.

### ISSUE THREAD

**Issue by suba-suresh** [suba-suresh/weather-web-app#10]
In order to **avoid getting information from a place in the wrong country** as a **user**, I can **select my country from the drop-down**
### Acceptance Criteria:
-  displays a drop-down menu with a list of countries(English countries like - Australia, Canada, New Zealand, Republic of Ireland), USA, and UK.
- user to select their country, and only shows information relevant to the selected country.
### Tasks:
- [x] Implement a drop-down menu populated with a list of countries
- [x]  filter displayed information based on the user's selection.
- [ ] make custom attributes for each country html option
- [ ] record attribute in js variable
- [ ] concatenate variable into api url next to city name
