### ISSUE TITLE
USER STORY : New Round Button

### ISSUE THREAD

**Issue by SteveBenton6** [suba-suresh/weather-web-app#13]
In order to **compete against a new computer choice** as a **user**, I can **press the ‘next round’ button**

### Acceptance Criteria:
 - A Next Round Button Is Visible on the site after the previous round has completed.
- The button clears the previous result and enables the user to enter a new location

### Tasks:
- [x] Create a Next Round Button in the HTML
- [x] Set up JS variable that indicates the DOM for the button location
- [x] Set up JS button click detector
- [x] Set up JS function to process activities to reset game when button is clicked
