### ISSUE TITLE
USER STORY : Welcome Message and Instruction

### ISSUE THREAD

**Issue by SteveBenton6** [suba-suresh/weather-web-app#16]
In order to **clearly understand what the website is about** as a **user**, I can **see a big orange container with a welcome message, brief explanation of what the website is for and what step one is**

### Acceptance Criteria:
- Welcome Message and Instruction Banner is Visible when joining site
- Banner is no longer visible when user clicks the search button for the weather forecast

### Tasks:
- [ ] Create HTML Location for Welcome Banner and Instructions
- [ ] Create Banner and Instruction Image and add to HTML
- [ ] Create JS variable storing Dom Location
- [ ] Create JS Function that removes visibility of Banner when search button is clicked.
