### ISSUE TITLE
USER STORY : a sum of how many wins I got

### ISSUE THREAD

**Issue by MarkChips** [suba-suresh/weather-web-app#22]
In order to **to see a sum of how many wins I got** as a **user**, I can **see the tally next to the text /6 at the bottom of the page**
### Acceptance Criteria:
- big text easily readible
- in a part of the page, obvious to the viewer
- correctly adds up user wins
- does not display until the user has search for a location
### Tasks:
- [x] add h2 elements above footer
- [x] add JS function which cumulates user wins and then inserts them into win/loss variable string
- [x] make JS hide/display win total at the right time
