### ISSUE TITLE
USER STORY : Computer Weather To Beat

### ISSUE THREAD

**Issue by SteveBenton6** [suba-suresh/weather-web-app#24]
In order to **see what the computer has chosen** as a **user**, I can **see the computer’s weather icon below the words ‘The weather to beat’**

### Acceptance Criteria:
- A Weather Symbol is displayed below the Weather To Beat

### Tasks:
- [x] HTML - Create Div/location to show Computer Weather to Beet Icon
- [x] JS - Create variable for DOM Location for Computer Weather
- [x] JS - Create Function to randomly pick computer Weather game Symbol
- [x] JS - Create Function to update DOM with randomly picked Weather
