### ISSUE TITLE
USER STORY : know which weather has beaten or been beaten by the computer’s choice

### ISSUE THREAD

**Issue by MarkChips** [suba-suresh/weather-web-app#25]
In order to **know which weather has beaten or been beaten by the computer’s choice** as a **user**, I can **see a + or - symbol below each days weather symbol**
### Acceptance Criteria:
- display + or - symbols next to each weather icon of the user's selection
- display = symbol for each weather that is a draw
### Tasks:
- [x] create JS function which creates a div of a +, -, or = depending on result
- [x] create a JS conditional statement which compares weather icons and returns the correct symbol depending on result
- [x] add HTML divs for the symbols to display within
- [x] add css styling so that symbols appear in small circles with either green, red, or blue to make it obvious whether they are positive or negative.
