### ISSUE TITLE
USER STORY : Display Who Won

### ISSUE THREAD

**Issue by SteveBenton6** [suba-suresh/weather-web-app#5]
In order to **clearly see who won the round** as a **user**, I can **see text at the bottom of the page which says ‘computer wins’ or ‘You won’**

### Acceptance Criteria:
- Statement Visible on Page Showing Who Won
- Accurate presentation of who win
- Wording correctly presented to show variations of who won
### Tasks:
- [x] Create Div location for Statement in HTML
- [x] Create variable(const) to record DOM Location for statement
- [x] Function to calculate winner
- [x] Function to process winner and provide statement to be shown in DOM
