### ISSUE TITLE
USER STORY : How to Play Button

### ISSUE THREAD

**Issue by SteveBenton6** [suba-suresh/weather-web-app#8]
In order to **to see information on how to play** as a **user**, I can **click the ‘how to play’ button found in the footer and see a diagram and steps appear in a pop up container**

### Acceptance Criteria:
- A clear How To Play Button is visible at the bottom.
- When the button is clicked information on how to play pops up.
- The information can be closed to allow game play.

### Tasks:
- [ ] Create Button in HTML
- [ ] Create variable to store DOM location of button
- [ ] Create event listener for button being clicked
- [ ] Create Modal with How to play info in
- [ ] Open modal when button is clicked.
- [ ] Have closure item on modal.
